[workspace]

resolver = "2"
members = [
    "suteravr-lib",
    "balancing-server",
    "clocking-server",
    "social-server",
    "client/rust"
]

[patch."https://github.com/godot-rust/godot4-prebuilt"] 
godot4-prebuilt = { git = "https://github.com//godot-rust/godot4-prebuilt", branch = "4.2"}
