[package]
name = "clocking-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alkahest = { version = "0.3.0", features = ["derive"] }
async-trait = "0.1.75"
once_cell = "1.19.0"
rustls = "0.22.1"
suteravr-lib = { path = "../suteravr-lib" }
thiserror = "1.0.52"
tokio = { version = "1.35.1", features = ["full"] }
